### ISSUE TITLE
Dual option of red/black Podvertka mark

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#9] opened 2019-02-21 13:04 UTC
We need to create a stylistic set option so that the Podvertka (RED by default) can be alternatively typeset in BLACK, in which case it also uses lookups to point to composite forms in the PUA.

> Explanation: In Type A and B notations, both systems allow for the presentation of the Podvertka in either red or black. Red is historically more accurate, as the Podvertka was introduced by Shaidur as a "markup" symbol below the right side of a base neume to indicate an extra descending note, where previously it was known to add the extra note through context. Over time, even in the Type B usage, the red mark SOMETIMES lost its color in certain contexts, but it was never firmly settled on, so we can find a dual usage of red or black, sometimes even in the same source. Note that its usage as a black mark was "in-line", rather than the red version being a "subscript" mark. See U+EAE1, EAE5, EAE9, EAEB, EAEF and EAF2 for black-podvertka composites. (This usage was also applied to the Statiya in certain popevki; the form with the red podvertka was mistaken for the Polukulizma Malaya, and so they ended up being conflated into a single all-black form.)

> The dual usage was carried over into Type A notation, which also added a black-composite version of the Palka with Podvertka (see U+EA9B and EA9D). Type B usage didn't make this switch.

**Comment by typiconman** [comment] 2019-03-22 12:41
So this can be done by creating a duplicate of U+1CF26 in the PUA, and creating a mapping to that glyph with the feature SS04.

**Comment by typiconman** [comment] 2019-04-09 08:34
This issue is now resolved.

**Closed as completed by typiconman** 2019-04-09 08:34 UTC
Labels: enhancement
